"""followers

Revision ID: 29457b24f45a
Revises: 7aec4e9c1639
Create Date: 2019-04-22 12:26:59.928157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29457b24f45a'
down_revision = '7aec4e9c1639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
