"""color

Revision ID: 59f032fc0d19
Revises: 29457b24f45a
Create Date: 2019-04-24 10:59:43.754819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f032fc0d19'
down_revision = '29457b24f45a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('color', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_color'), 'user', ['color'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_color'), table_name='user')
    op.drop_column('user', 'color')
    # ### end Alembic commands ###
